[build]
builder = "NIXPACKS"
watchPatterns = ["sabi/**"]

[deploy]
startCommand = "cd sabi && java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/sabi-0.0.1-SNAPSHOT.jar"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

